version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    container_name: checkvibe-backend
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    networks:
      - checkvibe

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    container_name: checkvibe-frontend
    networks:
      - checkvibe

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: always
    networks:
      - checkvibe

networks:
  checkvibe:
    driver: bridge