services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/prisma:/app/prisma
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - app-network



  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
  prisma_data: